### PR TITLE
Follow upstream changes

### PR DESCRIPTION
**Pull request by rufoa**
Hi @lsm5 

Could you merge the latest upstream changes please? The seccomp.json in your PPA debs currently lack `unshare`, among other calls, which causes problems for buildah-in-podman.

I can submit corresponding PRs for the other branches if this one looks good to you.
Thanks

### CODE REVIEW

**Comment by lsm5** [comment]
thanks @rufoa, btw I'm switching to OBS from PPA for ubuntu/debian builds. You can find them here:
https://build.opensuse.org/project/show/home:rhcontainerbot:stable (still wip) . My usual way to build deb packages is to rebase my deb packaging commits on the latest upstream release tag, so I'd prefer we get a new tag pushed upstream instead of merging this PR.

@vrothberg / @saschagrunert ping, you got access to push a new release tag for @seccomp/containers-golang repo with these commits?

**Comment by rufoa** [comment]
Thanks!

Will you be publishing builds of slirp4netns on OBS too, as you did on PPA? The version in Debian stable (third-party maintainer) is pretty old.

**Comment by vrothberg** [comment]
@lsm5, https://github.com/seccomp/containers-golang/releases/tag/v0.3.2

**Comment by lsm5** [comment]
thanks @vrothberg !!

@rufoa new containers-golang building at https://build.opensuse.org/package/show/home:rhcontainerbot:stable/containers-golang ... follow the `Download package` link at top right of that page to enable the repo for your system. Let me know if any issues.

I haven't built slirp4netns there yet, but I'll do that right away.

**Comment by lsm5** [comment]
@rufoa slirp4netns should be available for quite a bit of distros in there too now. If it's not available for your distro+arch combination yet, then it's probably some dependency issue, which I'll resolve with the OBS folks (hopefully soon).

Closing...

**Pull request closed without merging**
